# Default values for mychart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: mysql
  tag: "8.0"
  pullPolicy: IfNotPresent

mysqlRootPassword: phonders#1234
mysqlDatabase: userdb
mysqlUser: admin
mysqlPassword: phonders#1234

crudApp:
  image:
    repository: shoaib74/crud-app
    tag: latest
    pullPolicy: IfNotPresent

