# Default values for mychart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
mysql:
  image:
    repository: mysql
    tag: "8.0"
    pullPolicy: IfNotPresent
  rootPassword: phonders#1234
  database: userdb
  user: admin
  password: phonders#1234

crudApp:
  image:
    repository: shoaib74/crud-app
    tag: latest
    pullPolicy: IfNotPresent

hpa:
  minReplicas: 1
  maxReplicas: 3
  cpuUtilization: 50      
