apiVersion: v1
data:
  kibana.yml: "server.ssl:\n  enabled: true\n  key: /usr/share/kibana/config/certs/kibana-kibana-key.pem\n
    \ certificate: /usr/share/kibana/config/certs/kibana-kibana.pem\nxpack.security.encryptionKey:
    72c53eb2376164ebd971c25de25d88b7 \nxpack.encryptedSavedObjects.encryptionKey:
    f91b792ac5e1f9dfc1aebfcc56df3694\nxpack.reporting.encryptionKey: 44550d31fb728a7a59ea496db000d05c
    \nmonitoring.enabled: true\nmonitoring.kibana.collection.enabled: true\nelasticsearch.ssl:\n
    \ certificateAuthorities: /usr/share/kibana/config/elasticsearchcerts/ca.pem\n
    \ verificationMode: certificate\n"
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: kibana
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2023-03-29T17:12:16Z"
  labels:
    app: kibana
    app.kubernetes.io/managed-by: Helm
    heritage: Helm
    release: kibana
  name: kibana-kibana-config
  namespace: default
  resourceVersion: "117340"
  uid: 2eb70894-8d7f-47cb-bbdc-5ba73bbcdc98
